export const darkTheme = {
  mode: 'dark',
  FONT_FAMILY: 'Literata',
  PRIMARY_BACKGROUND_COLOR: '#FFFFFF',
  PRIMARY_TEXT_COLOR: '#767d92',
  SECONDARY_TEXT_COLOR: '#ffffff',
  PRIMARY_BUTTON_COLOR: '#152642',
  SECONDARY_BUTTON_COLOR: '#506680',
  PRIMARY_BUTTON_TEXT_COLOR: '#FFFFFF'
}

export const lightTheme = {
  mode: 'light',
  FONT_FAMILY: 'Rosario',
  PRIMARY_BACKGROUND_COLOR: '#ffefd5',
  PRIMARY_TEXT_COLOR: '#DB7093',
  SECONDARY_TEXT_COLOR: '#333333',
  PRIMARY_BUTTON_COLOR: '#b9d6f3',
  SECONDARY_BUTTON_COLOR: '#a1c9f1',
  PRIMARY_BUTTON_TEXT_COLOR: '#333333'
}
